export const ADD_TO_FIELD_VALUE = 'ADD_TO_FIELD_VALUE';
export const SET_LIST_ITEM = 'SET_LIST_ITEM';
export const DELETE_LIST_ITEM = 'DELETE_LIST_ITEM';
export const SET_CURRENT_LIST_ITEM = 'SET_CURRENT_LIST_ITEM';
