export const SET_FIELD_VALUE = 'SET_FIELD_VALUE';
export const ADD_LIST_ITEM = 'ADD_LIST_ITEM';
export const DELETE_LIST_ITEM = 'DELETE_LIST_ITEM';
export const SET_CURRENT_LIST_ITEM = 'SET_CURRENT_LIST_ITEM';
export const TOGGLE_CAPS_LOCK = 'TOGGLE_CAPS_LOCK';
export const TOGGLE_LANGUAGE = 'TOGGLE_LANGUAGE';
